<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTrafficSignClassTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('trafficsignclasses', function (Blueprint $table) {
            $table->increments('id');
            $table->integer("tsid")->default(0);
            $table->string("tscode", 20)->default("");
            $table->string("tsname", 50)->default("");
            
            $table->index(["tsid"]);
        });
        
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [1, "警1", "交叉路口"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [2, "警2", "急弯路"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [3, "警3", "反向弯路"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [4, "警4", "连续弯路"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [5, "警5", "陡坡"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [6, "警6", "连续下坡"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [7, "警7", "窄路"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [8, "警8", "窄桥"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [9, "警9", "双向交通"]);
        
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [10, "警10", "注意行人"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [11, "警11", "注意儿童"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [12, "警12", "注意牲畜"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [13, "警13", "注意野生动物"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [14, "警14", "注意信号灯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [15, "警15", "注意落石"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [16, "警16", "注意横风"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [17, "警17", "易滑"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [18, "警18", "傍山险路"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [19, "警19", "堤坝路"]);        
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [20, "警20", "村庄"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [21, "警21", "隧道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [22, "警22", "渡口"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [23, "警23", "驼峰桥"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [24, "警24", "路面不平"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [25, "警25", "路面高突"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [26, "警26", "路面低洼"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [27, "警27", "过水路面"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [28, "警28", "有人看守铁路道口"]);
        
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [29, "警29", "无人看守铁路道口"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [30, "警30", "叉形符号"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [31, "警31", "斜杠符号"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [32, "警32", "注意非机动车"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [33, "警33", "注意残疾人"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [34, "警34", "事故易发路段"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [35, "警35", "慢行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [36, "警36", "注意障碍物"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [37, "警37", "注意危险"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [38, "警38", "施工"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [39, "警39", "建议速度"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [40, "警40", "隧道开车灯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [41, "警41", "注意潮汐车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [42, "警42", "注意保持车距"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [43, "警43", "注意分离式道路"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [44, "警44", "注意合流"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [45, "警45", "避险车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [46, "警46", "注意路面结冰﹑注意雨(雪)天,注意雾天,注意不利气象条件"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [47, "瞥47", "注意前方车辆排队"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [48, "禁1", "停车让行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [49, "禁⒉", "减速让行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [50, "禁3", "会车让行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [51, "禁4", "禁止通行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [52, "禁5", "禁止驶人"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [53, "禁6", "禁止机动车驶入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [54, "禁7", "禁止载货汽车驶入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [55, "禁8", "禁止电动三轮车驶入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [56, "禁9", "禁止大型客车驶入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [57, "禁10", "禁止小型客车驶人"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [58, "禁11", "禁止挂车.半挂车驶入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [59, "禁12", "禁止拖拉机驶人"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [60, "禁13", "禁止三轮汽车.低速货车驶入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [61, "禁14", "禁止摩托车驶入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [62, "禁15", "禁止某两种车驶入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [63, "禁16", "禁止非机动车进入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [64, "禁17", "禁止畜力车进入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [65, "禁18", "禁止人力客运三轮车进入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [66, "禁19", "禁止人力货运三轮车进入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [67, "禁20", "禁止人力车进入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [68, "禁21", "禁止行人进人"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [69, "禁22", "禁止向左转弯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [70, "禁.23", "禁止向右转弯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [71, "禁24", "禁止直行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [72, "禁25", "禁止向左向右转弯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [73, "禁26", "禁止直行和向左转弯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [74, "禁27", "禁止直行和向右转弯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [75, "禁28", "禁止掉头"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [76, "禁29", "禁止超车"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [77, "禁30", "解除禁止超车"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [78, "禁31", "禁止停车"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [79, "禁32", "禁止长时停车"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [80, "禁33", "禁止鸣喇叭"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [81, "禁34", "限制宽度"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [82, "禁35", "限制高度"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [83, "禁36", "限制质量"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [84, "禁37", "限制轴重"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [85, "禁38", "限制速度"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [86, "禁39", "解除限制速度"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [87, "禁40", "停车检查"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [88, "禁41", "禁止运输危险物品车辆驶入"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [89, "禁42", "海关"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [90, "禁43", "区域限制速度"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [91, "禁44", "区域限制速度解除"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [92, "禁45", "区域禁止长时停车"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [93, "禁46", "区域禁止长时停车解除"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [94, "禁47", "区域禁止停车"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [95, "禁48", "区域禁止停车解除"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [96, "示1", "直行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [97, "示2", "向左转弯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [98, "示3", "向右转弯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [99, "示4", "直行和向左转弯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [100, "示5", "直行和向右转弯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [101, "示6", "向左和向右转弯"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [102, "示7", "靠右侧道路行驶"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [103, "示8", "靠左侧道路行驶"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [104, "示9", "立体交叉直行和左转弯行驶"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [105, "示10", "立体交叉直行和右转弯行驶"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [106, "示1l", "环岛行驶"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [107, "示12", "单行路(向左或向右)"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [108, "示13", "单行路(直行>"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [109, "示14", "步行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [110, "示15", "鸣喇叭"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [111, "示16", "最低限速"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [112, "示17", "路口优先通行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [113, "示18", "会车先行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [114, "示19", "人行横道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [115, "示20", "右转车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [116, "示21", "左转车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [117, "示22", "直行车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [118, "示23", "直行和右转合用车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [119, "示24", "直行和左转合用车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [120, "示25", "掉头车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [121, "示26", "掉头和左转合用车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [122, "示27", "分向行驶车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [123, "示28", "公交线路专用车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [124, "示29", "机动车行驶"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [125, "示30", "机动车车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [126, "示31", "非机动车行驶"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [127, "示32", "非机动车车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [128, "示33", "快速公交系统专用车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [129, "示34", "多乘员车辆专用车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [130, "示35", "停车位"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [131, "示36", "允许掉头"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [132, "路1", "四车道及以上公路交叉路口预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [133, "路2", "大交通量的四车道以上公路交叉路口预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [134, "路3", "箭头杆上标识公路编号,道路名称的公路交叉路口预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [135, "路4", "十字交叉路口"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [136, "路5", "丁字交叉路口"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [137, "路6", "Y型交叉路口"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [138, "路7", "环形交叉路口"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [139, "路8", "互通式立体交叉"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [140, "路9", "分岔处"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [141, "路10", "国道编号"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [142, "路11", "省道编号"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [143, "路12", "县道编号"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [144, "路13", "乡道编号"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [145, "路14", "街道名称"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [146, "路15", "路名牌"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [147, "路16", "地点距离"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [148, "路17", "地名"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [149, "路18", "著名地点"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [150, "路19", "行政区划分界"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [151, "路20", "道路管理分界"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [152, "路21", "地点识别"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [153, "路22", "停车场"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [154, "路23", "错车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [155, "路24", "人行天桥"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [156, "路25", "人行地下通道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [157, "路26", "残疾人专用设施"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [158, "路27", "观景台"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [159, "路28", "应急避难设施(场所)"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [160, "路29", "休息区"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [161, "路30", "绕行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [162, "路31", "此路不通"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [163, "路32", "车道数变少"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [164, "路33", "车道数增加"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [165, "路34", "交通监控设备"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [166, "路35", "隧道出口距离预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [167, "路36", "基本单元"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [168, "路37", "组合使用"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [169, "路38", "两侧通行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [170, "路39", "右侧通行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [171, "路40", "左侧通行"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [172, "路41", "入口预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [173, "路42", "地点.方向"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [174, "路43", "编号"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [175, "路44", "命名编号"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [176, "路45", "路名"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [177, "路46", "地点距离"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [178, "路47", "城市区域多个出口时的地点距离"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [179, "路48", "下一出口预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [180, "路49", "出口编号"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [181, "路50", "右侧出口预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [182, "路51", "左侧出口预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [183, "路52", "出口标志及出口地点方向"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [184, "路53", "高速公路起点"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [185, "路54", "终点预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [186, "路55", "终点提示"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [187, "路56", "国家高速公路、省级高速公路终点"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [188, "路57", "道路交通信息"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [189, "路58", "里程牌"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [190, "路59", "百米牌"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [191, "路60", "停车领卡"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [192, "路61", "车距确认"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [193, "路62", "特殊天气建议速度"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [194, "路63", "紧急电话"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [195, "路64", "电话位置指示"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [196, "路65", "救援电话"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [197, "路66", "不设电子不停车收费(ETC)车道的收费站预告及收费站"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [198, "路67", "设有电子不停车收费(ETC)车道的收费站预告及收费站"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [199, "路68", "ETC车道指示"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [200, "路69", "计重收费"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [201, "路70", "加油站"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [202, "路71", "紧急停车带"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [203, "路72", "服务区预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [204, "路73", "停车区预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [205, "路74", "停车场预告"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [206, "路75", "停车场"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [207, "路76", "爬坡车道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [208, "路77", "超限超载检测站"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [209, "路78", "设置在指路标志版面中的方向"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [210, "路79", "设置在指路标志版面外的方向"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [211, "旅1", "旅游区距离"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [212, "旅2", "旅游区方向"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [213, "旅3", "何讯处"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [214, "旅4", "徒步"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [215, "旅5", "索道"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [216, "旅6", "野营地"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [217, "旅7", "营火"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [218, "旅8", "游戏场"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [219, "旅9", "骑马"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [220, "旅10", "钓鱼"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [221, "旅11", "高尔夫球"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [222, "旅12", "潜水"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [223, "旅13", "游泳"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [224, "旅14", "划船"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [225, "旅15", "冬季游览区"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [226, "旅16", "滑雪"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [227, "旅17", "滑冰"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [228, "辅1", "时间范围"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [229, "辅⒉", "除公共汽车外"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [230, "辅3", "机动车"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [231, "辅4", "货车"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [232, "辅5", "货车﹑拖拉机"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [233, "辅6", "私人专属"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [234, "辅7", "行驶方向标志"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [235, "辅8", "向前200m"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [236, "辅9", "向左100m"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [237, "辅10", "向左、向右各50m"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [238, "辅11", "向右100m"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [239, "辅12", "某区域内"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [240, "辅13", "距离某地200m"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [241, "辅14", "长度"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [242, "辅15", "学校"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [243, "辅16", "海关"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [244, "辅17", "事故"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [245, "辅18", "塌方"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [246, "辅19", "教练车行驶路线"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [247, "辅20", "驾驶考试路线"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [248, "辅21", "校车停靠站点"]);
        DB::insert("insert into trafficsignclasses (tsid, tscode, tsname) values(?, ?, ?) ", [249, "辅22", "组合辅助"]);
        
        
        
//        insert into trafficsignclasses (tsid, tscode, tsname) values(1, '警1', '交叉路口');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(2, '警2', '急弯路');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(3, '警3', '反向弯路');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(4, '警4', '连续弯路');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(5, '警5', '陡坡');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(6, '警6', '连续下坡');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(7, '警7', '窄路');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(8, '警8', '窄桥');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(9, '警9', '双向交通');
//
//        insert into trafficsignclasses (tsid, tscode, tsname) values(10, '警10', '注意行人');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(11, '警11', '注意儿童');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(12, '警12', '注意牲畜');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(13, '警13', '注意野生动物');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(14, '警14', '注意信号灯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(15, '警15', '注意落石');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(16, '警16', '注意横风');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(17, '警17', '易滑');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(18, '警18', '傍山险路');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(19, '警19', '堤坝路');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(20, '警20', '村庄');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(21, '警21', '隧道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(22, '警22', '渡口');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(23, '警23', '驼峰桥');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(24, '警24', '路面不平');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(25, '警25', '路面高突');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(26, '警26', '路面低洼');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(27, '警27', '过水路面');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(28, '警28', '有人看守铁路道口');
//
//        insert into trafficsignclasses (tsid, tscode, tsname) values(29, '警29', '无人看守铁路道口');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(30, '警30', '叉形符号');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(31, '警31', '斜杠符号');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(32, '警32', '注意非机动车');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(33, '警33', '注意残疾人');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(34, '警34', '事故易发路段');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(35, '警35', '慢行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(36, '警36', '注意障碍物');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(37, '警37', '注意危险');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(38, '警38', '施工');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(39, '警39', '建议速度');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(40, '警40', '隧道开车灯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(41, '警41', '注意潮汐车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(42, '警42', '注意保持车距');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(43, '警43', '注意分离式道路');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(44, '警44', '注意合流');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(45, '警45', '避险车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(46, '警46', '注意路面结冰﹑注意雨(雪)天,注意雾天,注意不利气象条件');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(47, '瞥47', '注意前方车辆排队');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(48, '禁1', '停车让行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(49, '禁⒉', '减速让行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(50, '禁3', '会车让行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(51, '禁4', '禁止通行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(52, '禁5', '禁止驶人');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(53, '禁6', '禁止机动车驶入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(54, '禁7', '禁止载货汽车驶入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(55, '禁8', '禁止电动三轮车驶入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(56, '禁9', '禁止大型客车驶入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(57, '禁10', '禁止小型客车驶人');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(58, '禁11', '禁止挂车.半挂车驶入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(59, '禁12', '禁止拖拉机驶人');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(60, '禁13', '禁止三轮汽车.低速货车驶入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(61, '禁14', '禁止摩托车驶入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(62, '禁15', '禁止某两种车驶入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(63, '禁16', '禁止非机动车进入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(64, '禁17', '禁止畜力车进入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(65, '禁18', '禁止人力客运三轮车进入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(66, '禁19', '禁止人力货运三轮车进入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(67, '禁20', '禁止人力车进入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(68, '禁21', '禁止行人进人');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(69, '禁22', '禁止向左转弯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(70, '禁.23', '禁止向右转弯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(71, '禁24', '禁止直行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(72, '禁25', '禁止向左向右转弯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(73, '禁26', '禁止直行和向左转弯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(74, '禁27', '禁止直行和向右转弯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(75, '禁28', '禁止掉头');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(76, '禁29', '禁止超车');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(77, '禁30', '解除禁止超车');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(78, '禁31', '禁止停车');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(79, '禁32', '禁止长时停车');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(80, '禁33', '禁止鸣喇叭');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(81, '禁34', '限制宽度');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(82, '禁35', '限制高度');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(83, '禁36', '限制质量');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(84, '禁37', '限制轴重');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(85, '禁38', '限制速度');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(86, '禁39', '解除限制速度');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(87, '禁40', '停车检查');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(88, '禁41', '禁止运输危险物品车辆驶入');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(89, '禁42', '海关');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(90, '禁43', '区域限制速度');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(91, '禁44', '区域限制速度解除');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(92, '禁45', '区域禁止长时停车');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(93, '禁46', '区域禁止长时停车解除');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(94, '禁47', '区域禁止停车');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(95, '禁48', '区域禁止停车解除');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(96, '示1', '直行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(97, '示2', '向左转弯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(98, '示3', '向右转弯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(99, '示4', '直行和向左转弯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(100, '示5', '直行和向右转弯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(101, '示6', '向左和向右转弯');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(102, '示7', '靠右侧道路行驶');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(103, '示8', '靠左侧道路行驶');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(104, '示9', '立体交叉直行和左转弯行驶');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(105, '示10', '立体交叉直行和右转弯行驶');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(106, '示1l', '环岛行驶');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(107, '示12', '单行路(向左或向右)');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(108, '示13', '单行路(直行>');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(109, '示14', '步行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(110, '示15', '鸣喇叭');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(111, '示16', '最低限速');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(112, '示17', '路口优先通行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(113, '示18', '会车先行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(114, '示19', '人行横道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(115, '示20', '右转车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(116, '示21', '左转车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(117, '示22', '直行车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(118, '示23', '直行和右转合用车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(119, '示24', '直行和左转合用车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(120, '示25', '掉头车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(121, '示26', '掉头和左转合用车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(122, '示27', '分向行驶车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(123, '示28', '公交线路专用车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(124, '示29', '机动车行驶');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(125, '示30', '机动车车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(126, '示31', '非机动车行驶');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(127, '示32', '非机动车车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(128, '示33', '快速公交系统专用车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(129, '示34', '多乘员车辆专用车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(130, '示35', '停车位');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(131, '示36', '允许掉头');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(132, '路1', '四车道及以上公路交叉路口预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(133, '路2', '大交通量的四车道以上公路交叉路口预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(134, '路3', '箭头杆上标识公路编号,道路名称的公路交叉路口预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(135, '路4', '十字交叉路口');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(136, '路5', '丁字交叉路口');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(137, '路6', 'Y型交叉路口');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(138, '路7', '环形交叉路口');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(139, '路8', '互通式立体交叉');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(140, '路9', '分岔处');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(141, '路10', '国道编号');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(142, '路11', '省道编号');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(143, '路12', '县道编号');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(144, '路13', '乡道编号');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(145, '路14', '街道名称');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(146, '路15', '路名牌');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(147, '路16', '地点距离');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(148, '路17', '地名');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(149, '路18', '著名地点');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(150, '路19', '行政区划分界');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(151, '路20', '道路管理分界');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(152, '路21', '地点识别');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(153, '路22', '停车场');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(154, '路23', '错车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(155, '路24', '人行天桥');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(156, '路25', '人行地下通道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(157, '路26', '残疾人专用设施');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(158, '路27', '观景台');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(159, '路28', '应急避难设施(场所)');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(160, '路29', '休息区');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(161, '路30', '绕行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(162, '路31', '此路不通');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(163, '路32', '车道数变少');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(164, '路33', '车道数增加');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(165, '路34', '交通监控设备');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(166, '路35', '隧道出口距离预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(167, '路36', '基本单元');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(168, '路37', '组合使用');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(169, '路38', '两侧通行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(170, '路39', '右侧通行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(171, '路40', '左侧通行');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(172, '路41', '入口预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(173, '路42', '地点.方向');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(174, '路43', '编号');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(175, '路44', '命名编号');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(176, '路45', '路名');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(177, '路46', '地点距离');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(178, '路47', '城市区域多个出口时的地点距离');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(179, '路48', '下一出口预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(180, '路49', '出口编号');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(181, '路50', '右侧出口预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(182, '路51', '左侧出口预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(183, '路52', '出口标志及出口地点方向');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(184, '路53', '高速公路起点');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(185, '路54', '终点预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(186, '路55', '终点提示');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(187, '路56', '国家高速公路、省级高速公路终点');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(188, '路57', '道路交通信息');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(189, '路58', '里程牌');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(190, '路59', '百米牌');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(191, '路60', '停车领卡');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(192, '路61', '车距确认');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(193, '路62', '特殊天气建议速度');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(194, '路63', '紧急电话');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(195, '路64', '电话位置指示');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(196, '路65', '救援电话');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(197, '路66', '不设电子不停车收费(ETC)车道的收费站预告及收费站');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(198, '路67', '设有电子不停车收费(ETC)车道的收费站预告及收费站');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(199, '路68', 'ETC车道指示');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(200, '路69', '计重收费');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(201, '路70', '加油站');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(202, '路71', '紧急停车带');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(203, '路72', '服务区预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(204, '路73', '停车区预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(205, '路74', '停车场预告');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(206, '路75', '停车场');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(207, '路76', '爬坡车道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(208, '路77', '超限超载检测站');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(209, '路78', '设置在指路标志版面中的方向');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(210, '路79', '设置在指路标志版面外的方向');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(211, '旅1', '旅游区距离');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(212, '旅2', '旅游区方向');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(213, '旅3', '何讯处');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(214, '旅4', '徒步');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(215, '旅5', '索道');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(216, '旅6', '野营地');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(217, '旅7', '营火');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(218, '旅8', '游戏场');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(219, '旅9', '骑马');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(220, '旅10', '钓鱼');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(221, '旅11', '高尔夫球');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(222, '旅12', '潜水');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(223, '旅13', '游泳');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(224, '旅14', '划船');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(225, '旅15', '冬季游览区');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(226, '旅16', '滑雪');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(227, '旅17', '滑冰');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(228, '辅1', '时间范围');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(229, '辅⒉', '除公共汽车外');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(230, '辅3', '机动车');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(231, '辅4', '货车');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(232, '辅5', '货车﹑拖拉机');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(233, '辅6', '私人专属');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(234, '辅7', '行驶方向标志');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(235, '辅8', '向前200m');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(236, '辅9', '向左100m');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(237, '辅10', '向左、向右各50m');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(238, '辅11', '向右100m');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(239, '辅12', '某区域内');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(240, '辅13', '距离某地200m');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(241, '辅14', '长度');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(242, '辅15', '学校');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(243, '辅16', '海关');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(244, '辅17', '事故');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(245, '辅18', '塌方');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(246, '辅19', '教练车行驶路线');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(247, '辅20', '驾驶考试路线');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(248, '辅21', '校车停靠站点');
//        insert into trafficsignclasses (tsid, tscode, tsname) values(249, '辅22', '组合辅助');        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('trafficsignclasses');
    }
}
